const NAMESPACE = 'win';

export const FETCH_EVENTS_REQUEST = `${NAMESPACE}/FETCH_EVENTS_REQUEST`;
export const FETCH_EVENTS_SUCCESS = `${NAMESPACE}/FETCH_EVENTS_SUCCESS`;
export const FETCH_EVENTS_ERROR = `${NAMESPACE}/FETCH_EVENTS_ERROR`;
